### ISSUE TITLE
Unable to read GCLOUD_PROJECT

### ISSUE THREAD

**Issue by abawany** [captiz/winston-googlecloud#1]
I am using the module as specified in the example:

```
var winston = require('winston');
...
require('winston-googlecloud');
var opts = {
  level: 'verbose',
  gcl_proj_id: 'my-project-id',
  ...
};
winston.add(winston.transports.GoogleCloudLogging, options);
```

In addition, the `GCLOUD_PROJECT` is also defined as `'my-project-id'`. On startup, I get the following error:

```
$BASE/node_modules/winston-googlecloud/node_modules/gcloud/lib/common/util.js:541
    throw util.missingProjectIdError;
    ^

Error: Sorry, we cannot connect to Google Cloud Services without a project ID. You may specify one with an environment variable named "GCLOUD_PROJECT". See https://googlecloudplatform.github.io/gcloud-node/#/authentication for a detailed guide on creating an authenticated connection.
    at Object.<anonymous> ($BASE/node_modules/winston-googlecloud/node_modules/gcloud/lib/common/util.js:47:29)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> ($BASE/node_modules/winston-googlecloud/node_modules/gcloud/lib/common/service-object.js:31:12)
    at Module._compile (module.js:541:32)
```

**Comment by abawany** [comment]
User error: should be `gcl_project_id` not `gcl_proj_id`. Desole.
